@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.token}}

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "securepassword123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "securepassword123"
}

###

# @name get_profile
GET {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name refresh_token
PATCH {{baseUrl}}/token/refresh
